packages:
  - "."

minimumReleaseAge: 1440
strictDepBuilds: false

overrides:
  conventional-changelog-conventionalcommits: 8.0.0
  lodash: 4.17.23
  lodash-es: 4.17.23

onlyBuiltDependencies:
  - '@vue-office/docx'
  - '@vue-office/excel'
  - '@vue-office/pdf'
  - '@vue-office/pptx'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - tlbs-map-vue
  - vue-demi

allowBuilds:
  '@parcel/watcher': false
  '@vue-office/docx': true
  '@vue-office/excel': true
  '@vue-office/pdf': true
  '@vue-office/pptx': true
  esbuild: false
  sharp: false
  tlbs-map-vue: false
  vue-demi: false
